name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint com Ruff
        run: ruff check .
      - name: Verificar formatação com Black
        run: black --check .
      - name: Type check com mypy
        run: mypy .
      - name: Executar testes
        run: pytest
